version: '3'
services:
  web:
    container_name: web
    image: kryptos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:80"
    environment:
      - FLASK_DEBUG=0
      - FLASK_ENV='prod'
      - FLASK_APP=autoapp.py
      - REDIS_HOST=redis
      - DATABASE_URL=postgres://postgres:postgres@db:5432/kryptos
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - redis
      - db
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"\
    # command: ['flask', 'run']

  worker:
    image: kryptos
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - catalyst:/root/.catalyst

    entrypoint: ['python', 'kryptos/worker/worker.py']
    depends_on:
    - redis

  ingester:
    image: kryptos
    container_name: ingester
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - catalyst:/root/.catalyst
    entrypoint: ['python', 'kryptos/worker/ingester.py']
    depends_on:
    - worker

  db:
    container_name: db
    image: postgres:10.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'kryptos'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  redis:
    container_name: redis
    image: redis:4.0.5-alpine


volumes:
  catalyst:
  postgres_data:
