version: '3'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - .:/app
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    # command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
# command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
  redis:
    image: redis:alpine
    # command: ["redis-server", "--appendonly", "yes"]
    # hostname: localhost
    # networks:
    #   - redis-net
    # volumes:
    #   - redis-data:/data

  # rq:
  #   build: .
  #   command: ["python", "/app/kryptos/app/utils/worker.py"]
  #   volumes:
  #    - .:/app