version: '3'
services:
  web:
    container_name: web
    image: kryptos-main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     # - "80:80"
     - "5000:5000"
    volumes:
     - .:/app
     # - ~/.catalyst:/root/catalyst #to store exhange data and auth
    environment:
      - FLASK_DEBUG=${DEBUG:-True}
      - REDIS_HOST=redis
      # - LISTEN_PORT=80
    networks:
      - kryptos-net
    depends_on:
      - redis
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"\
    command: ['flask', 'run']

  worker:
    image: kryptos-main
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile

    entrypoint: ["rqworker", "-u", "redis://redis:6379"]
    networks:
      - kryptos-net

    depends_on:
    - redis

  redis:
    container_name: redis
    image: redis:4.0.5-alpine
    networks:
      - kryptos-net

networks:
  kryptos-net: