version: '3'
services:
  web:
    container_name: web
    image: kryptos-local-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    volumes:
     - ./app:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=docker-dev
      # uses docker redis and db, but fetches other credentials from datastore
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_APP=autoapp.py
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:postgres@db:5432/kryptos
      - GOOGLE_APPLICATION_CREDENTIALS=/app/Kryptos-Staging-3deb8860d570.json
      - CONFIG_ENV=dev
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - db
    # # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"\
    entrypoint: ['honcho', 'start', 'dev', '--no-prefix']

  updater:
    container_name: updater
    image: kryptos-local-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
     - "9181:9181" # for rq-dashboard

    volumes:
     - ./app:/app
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - CONFIG_ENV=dev
     - GOOGLE_APPLICATION_CREDENTIALS=/app/Kryptos-Staging-3deb8860d570.json
    depends_on:
      - redis
      - db
    entrypoint: ['honcho', 'start', 'updater', '--no-prefix']

  worker:
    image: kryptos-local-worker
    container_name: worker
    build:
      context: ./core
      dockerfile: Dockerfile
    volumes:
      # - catalyst:/root/.catalyst
      - ./core:/core
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_APPLICATION_CREDENTIALS=Kryptos-Staging-3deb8860d570.json
      - PYTHONUNBUFFERED=1
      - CONFIG_ENV=dev

    # entrypoint: ['python', 'worker.py']
    entrypoint: ['honcho', 'start', 'worker', '--no-prefix']
    depends_on:
    - redis

  ml:
    image: kryptos-local-ml
    container_name: ml
    build:
      context: ./ml
      dockerfile: Dockerfile
    volumes:
      - ./ml:/ml
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GOOGLE_APPLICATION_CREDENTIALS=Kryptos-Staging-3deb8860d570.json

    depends_on:
    - redis


  db:
    container_name: db
    image: postgres:10.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'kryptos'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

     # expose port 5433 instead of default
     # in case postgres already on host machine
    ports:
      - "5433:5432"

  redis:
    container_name: redis
    image: redis:4.0.5-alpine
    command: redis-server


volumes:
  catalyst:
  postgres_data:
