steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/kryptos-worker']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/kryptos-worker',
            # '--cache-from', 'gcr.io/$PROJECT_ID/kryptos-worker',
            'core/'
        ]

images: ['gcr.io/$PROJECT_ID/kryptos-worker']
timeout: '1500s'
