steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/kryptos-app:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/kryptos-app:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/kryptos-app:latest',
            'app/'
        ]

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", 'app/app.yaml', '--image-url=gcr.io/$PROJECT_ID/kryptos-app:latest']

images: ['gcr.io/$PROJECT_ID/kryptos-app:latest']
